spring:
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/driverservice?useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true&connectTimeout=10000&socketTimeout=30000
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 10000
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: validate # Changed from update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        connection.provider_disables_autocommit: true
    show-sql: true

server:
  port: 8080